### ISSUE TITLE
SHC: Permission Viewer Roles Still broken?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [JustOptimize/ShowHiddenChannels#197]
Is this ever going to get fixed?
<img width="668" alt="Screen Shot 2024-08-04 at 13 44 29 pm" src="https://github.com/user-attachments/assets/65e33a8c-619a-458f-8ca5-430e26916887">

I'd really like to see what roles they are & not just invisible boxes, I can still get the ID of each one & manually find out by doing `<@&>` thing

its been broken like this for a long time btw..

**Comment by JustOptimize** [comment]
It's been fixed since April thanks to @ShaneMcC that implemented the same fix as when ShowHiddenChannels had the same issue.
Zerebos hasn't merged the [pull request](https://github.com/rauenzi/BetterDiscordAddons/pull/759) god knows why.

Here's the fixed plugin's link https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/25498956b3dcd484eeb93506a9c39c7d3b68570c/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

**Comment by XxUnkn0wnxX** [comment]
ah thanks, I thought this was apart of SHC since I recalled the original one had this feature built-in
